export const canvasItems = [
  {
    numbering: "01",
    title: "Bokey",
    sub_title: "bokeh",
    created_at: "september, fifth",
    color: "#D94034",
  },
  {
    numbering: "02",
    title: "Combell's<br>Soup 3D",
    sub_title: "campbell's soup 3d",
    created_at: "september, fifth",
    color: "#CC382B",
  },
  {
    numbering: "03",
    title: "Univere<br>Panorama",
    sub_title: "universe panorama",
    created_at: "september, fifth",
    color: "#C13226",
  },
  {
    numbering: "04",
    title: "Color<br>Pixelated",
    sub_title: "color pixelated",
    created_at: "september, fifth",
    color: "#FFC801",
  },
  {
    numbering: "05",
    title: "Spiral",
    sub_title: "spiral",
    created_at: "september, fifth",
    color: "#EFBB01",
  },
  {
    numbering: "06",
    title: "Triangulat-<br>icon",
    sub_title: "triangulation",
    created_at: "september, fifth",
    color: "#E1B000",
  },
  {
    numbering: "",
    title: "",
    sub_title: "",
    created_at: "",
    disable: true,
    color: "#222222",
  },
  {
    numbering: "",
    title: "",
    sub_title: "",
    created_at: "",
    disable: true,
    color: "#222222",
  },
  {
    numbering: "",
    title: "",
    sub_title: "",
    created_at: "",
    disable: true,
    color: "#222222",
  },
  {
    numbering: "",
    title: "",
    sub_title: "",
    created_at: "",
    disable: true,
    color: "#222222",
  },
  {
    numbering: "",
    title: "",
    sub_title: "",
    created_at: "",
    disable: true,
    color: "#222222",
  },
  {
    numbering: "07",
    title: "Hue<br>Blending",
    sub_title: "hue blending",
    created_at: "september, fifth",
    color: "#93C84A",
  },
  {
    numbering: "08",
    title: "Flip Clock",
    sub_title: "flip clock",
    created_at: "september, fifth",
    color: "#82BA3A",
  },
  {
    numbering: "09",
    title: "Ripples on<br>the<br>Green",
    sub_title: "ripples on the green",
    created_at: "september, fifth",
    color: "#80B23B",
  },
  {
    numbering: "10",
    title: "Raining<br>Men",
    sub_title: "raining men",
    created_at: "september, fifth",
    color: "#27A6C0",
  },
  {
    numbering: "11",
    title: "surface waves",
    sub_title: "",
    created_at: "september, fifth",
    color: "#2091A9",
  },
  {
    numbering: "12",
    title: "Plant Trees",
    sub_title: "plant trees",
    created_at: "september, fifth",
    color: "#2091A9",
  },
  {
    numbering: "12",
    sub_title: "",
    title: "Plant Trees",
    created_at: "september, fifth",
    color: "#2091A9",
  },
  {
    numbering: "13",
    title: "Wiper<br>Typography",
    sub_title: "wiper typography",
    created_at: "september, fifth",
    color: "#5F57CA",
  },
  {
    numbering: "14",
    title: "The Scream",
    sub_title: "the scream",
    created_at: "september, fifth",
    color: "#544CBA",
  },
  {
    numbering: "15",
    title: "Sheep",
    sub_title: "sheep",
    created_at: "september, fifth",
    color: "#4A42AD",
  },

  //여기부터 다시 고민해봅시다. (내가 추가해도 괜찮을 듯 => 5개 정도는 내 아이디어로?)
  {
    title: "Plant Trees",
    created_at: "september, fifth",
    color: "green",
  },
  {
    title: "Plant Trees",
    created_at: "september, fifth",
    color: "green",
  },
  {
    title: "Plant Trees",
    created_at: "september, fifth",
    color: "green",
  },
  {
    title: "Plant Trees",
    created_at: "september, fifth",
    color: "green",
  },
  {
    title: "Plant Trees",
    created_at: "september, fifth",
    color: "green",
  },
];
